---
development:
  cloud_name: hacavcdca
  api_key: '986229117884369'
  api_secret: DQWHGYIw4OfXL4pEKMd7X6gdag0
  enhance_image_tag: true
  static_image_support: true
production:
  cloud_name: hacavcdca
  api_key: '986229117884369'
  api_secret: DQWHGYIw4OfXL4pEKMd7X6gdag0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hacavcdca
  api_key: '986229117884369'
  api_secret: DQWHGYIw4OfXL4pEKMd7X6gdag0
  enhance_image_tag: true
  static_image_support: false
